# Generated by Django 3.2.8 on 2021-10-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20211013_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='prof_pic',
            field=models.ImageField(default='default.jpg', upload_to='pics/'),
        ),
    ]
