# Generated by Django 3.2.8 on 2021-10-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_myuser_prof_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='prof_pic',
            field=models.ImageField(default='default.jpg', upload_to='pics/'),
        ),
    ]
