# Generated by Django 3.2.8 on 2021-10-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_myuser_prof_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='prof_pic',
            field=models.ImageField(default=None, upload_to='pics/'),
        ),
    ]
