# Generated by Django 3.2.8 on 2021-10-08 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='author',
        ),
    ]
